**What is NumPy?**

NumPy (Numerical Python) is the core library for numerical computing in Python.
It provides:

* Multi-dimensional arrays (ndarray)

* Mathematical functions (linear algebra, statistics, etc.)

* Fast array operations (much faster than native Python lists)

In [2]:
# pip install numpy
import numpy as np

**Creating NumPy Arrays**


1D Array (Vector)

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


2D Array (Matrix)

In [4]:
matrix = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(matrix)

[[1 2 3 4 5]
 [6 7 8 9 0]]


3D Array

In [5]:
tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tensor)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


 Array Attributes


In [7]:
print(arr.shape)       # (3,) – 1D array with 3 elements
print(matrix.ndim)     # 2 – 2D matrix
print(tensor.size)     # 8 – total number of elements


(5,)
2
8


 Step 4: Useful Array Creation Methods

In [8]:
np.zeros((2, 3))        # 2x3 matrix filled with 0s
np.ones((3, 3))         # 3x3 matrix of 1s
np.eye(3)               # Identity matrix
np.arange(0, 10, 2)     # [0 2 4 6 8]
np.linspace(0, 1, 5)    # 5 equally spaced numbers from 0 to 1


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

 Step 5: Basic Array Operations


In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)      # [5 7 9]
print(a * 2)      # [2 4 6]
print(a ** 2)     # [1 4 9]
print(np.dot(a, b))  # 32 – Dot product


[5 7 9]
[2 4 6]
[1 4 9]
32


 Indexing & Slicing


In [10]:
matrix = np.array([[10, 20], [30, 40], [50, 60]])

print(matrix[0, 1])     # 20
print(matrix[1:, :])    # [[30, 40], [50, 60]]


20
[[30 40]
 [50 60]]


RESHAPING

📌Reshape: arr.reshape(new-shape)

In [14]:
a = np.arange(12)  # [0 1 2 ... 11]
print(a.reshape(3, 4))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


 Flatten: Convert to 1D


In [15]:
a.reshape(-1)
a.flatten()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

 Stacking Arrays


In [18]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

np.vstack((a, b))  # Stack vertically
np.hstack((a, b))  # Stack horizontally


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

**Aggregations**

📌Common Functions: np.sum(), np.mean(), np.min(), np.max(), np.std()
Axis Control:axis=0 (columns), axis=1 (rows)

In [19]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])

print(matrix.sum())         # 21
print(matrix.mean())        # 3.5
print(matrix.std())         # 1.7078
print(matrix.max(axis=0))   # [4 5 6] — max in each column


21
3.5
1.707825127659933
[4 5 6]


**some advanced**

 How do you handle NaNs or Infs in a NumPy array?

In [ ]:
np.isnan(arr)        # Detect NaNs
np.isinf(arr)        # Detect Infs
np.nan_to_num(arr)   # Replace NaNs with 0


💬 Interview Questions with Powerful Answers

❓ Q1: What is the difference between a Python list and a NumPy array?

List: General-purpose, can store mixed data types, slower

NumPy Array: Fixed-type, supports vectorized operations (faster)

❓ Q2: What are broadcasting rules in NumPy?

Broadcasting allows arithmetic operations on arrays of different shapes.

E.g., adding a scalar to a 2D array or aligning a row vector across multiple rows.

❓ Q3: How does NumPy achieve speed over regular Python lists?

* Uses C-level optimizations under the hood

* Supports vectorized operations without Python loops

* Compact contiguous memory blocks

